---
title: Jekyll Portal
timezone: UTC
collections:
  portfolio:
    title: Portfolio
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo
backend:
  name: github
  repo: Dasapugo4444/jekyll-portal
