---
title: Jekyll Portal
timezone: UTC
collections:
  portfolio:
    title: Portfolio
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
_editable_regions:
  image:
    url_src: true
_source_editor:
  tab_size: 4
  theme: clouds_midnight
