backend:
  name: github
  repo: Dasapugo4444/jekyll-portal
publish_mode: editorial_workflow
media_folder: "/img/uploads" # Media files will be stored in the repo under images/uploads
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Cuerpo", name: "body", widget: "markdown"}
  - name: "portfolio"
    label: "Portafolio"
    folder: "_portfolio"
    create: true
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Imagen", name: "image_path", widget: "image"}
      - {label: "Proyecto", name: "project_name", widget: "string"}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Categorías", name: "categories", widget: "string"}
  - name: "pages"
    label: "Páginas"
    folder: "_pages"
    create: true
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Ruta", name: "permalink", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Cuerpo", name: "body", widget: "markdown"}
  - label: "Data"
    name: "data"
    folder: "_data"
    create: true
    fields:
      - {label: "Cuerpo", name: "body", widget: "string"}